import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProvider } from "./provider";
import { handleAppBarSignIn, handleSignOut } from "./actions";
import { Appbar } from "@repo/ui/appbar";
import { auth } from "@/auth";





const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-[#F9F8F6] text-stone-800`}>
        <AppProvider>
          <Appbar user={user} onSignin={handleAppBarSignIn} onSignout={handleSignOut}></Appbar>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
